// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnNirtVUh0CaTo0k0Vz8fI4t9LKN_irjk',
    appId: '1:369525553537:web:11328971b0c424991f5080',
    messagingSenderId: '369525553537',
    projectId: 'cp-fitness-f1a68',
    authDomain: 'cp-fitness-f1a68.firebaseapp.com',
    storageBucket: 'cp-fitness-f1a68.appspot.com',
    measurementId: 'G-4FMGNYR6C9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC73NzDx_pQO-foRJTBnmMa3Ut7uxIyR4s',
    appId: '1:369525553537:android:d53fd04ae8474d811f5080',
    messagingSenderId: '369525553537',
    projectId: 'cp-fitness-f1a68',
    storageBucket: 'cp-fitness-f1a68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgf1pQM_90FWCWN15VXdERiaX4hPtIzTA',
    appId: '1:369525553537:ios:d2fe7207c6914e4a1f5080',
    messagingSenderId: '369525553537',
    projectId: 'cp-fitness-f1a68',
    storageBucket: 'cp-fitness-f1a68.appspot.com',
    iosBundleId: 'com.example.cpFitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgf1pQM_90FWCWN15VXdERiaX4hPtIzTA',
    appId: '1:369525553537:ios:9714719b6eedb2941f5080',
    messagingSenderId: '369525553537',
    projectId: 'cp-fitness-f1a68',
    storageBucket: 'cp-fitness-f1a68.appspot.com',
    iosBundleId: 'com.example.cpFitnessApp.RunnerTests',
  );
}
